### ISSUE TITLE
Create GitHub labels

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-finance-purchasing#1]
@mateoclarke 

I realized I create this repo and you may not have seen it. Is it possible to update this repo with our default labels as some point? 

Thanks!

**Comment by mateoclarke** [comment]
Got it. Will do with the next batch of label updates

**Comment by dianamartin** [comment]
John showed me how to copy the .yml file, but it doesn't have the label descriptions on them. I guess during the meeting you were just going to update the existing .yml file?

**Comment by mateoclarke** [comment]
this is done.
