### ISSUE TITLE
Account Access: M. Benton

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-knack-finance-purchasing#46]
Marisol B. 
OOD

emailed me
>I’m having issues logging into the Knack system is this something you can help me with?

![image](https://user-images.githubusercontent.com/21112975/68238802-73f10800-ffcf-11e9-9b7e-1c21ef12f4d8.png)

**Comment by dianamartin** [comment]
I emailed Marisol to see if she could get on a screen share/call so that I could see what was happening. When she tried to log in using the COACD button, she'd get an error message. It referenced a different email address than her work email. 

I called CTM to see if they could identify the issue. The help desk agent said they'd have to remote in to fix the issue. Have reached out to the user to get computer name so that CTM can remote in and fix the problem.

**Comment by amenity** [comment]
@dianamartin check w/ Marisol

**Comment by dianamartin** [comment]
Had instructed Marisol to call CTM to get this issue resolved. 

Emailed user today (11/18)
>Just following up on this. Did you get this resolved with CTM and are able to log into the Finance and Purchasing app with your COACD credentials? I’m trying to close the issue I have open regarding this issue you have.

**Comment by dianamartin** [comment]
User emailed to confirm it's working
>Yes ma’am it’s working.
